services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=buffet'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=dev'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/buffet'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data:
